name: CodeQuality

on: pull_request

jobs:
  qa:
    name: CodeQuality
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, macos-latest]
        include:
          - node-version: 15.x
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache-node-modules
        with:
          path: node_modules
          key: install-${{ runner.OS }}-v${{ matrix.node-version }}-${{ hashFiles('package.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run lint
        run: npx carna lint --ci

      - name: Run test
        run: npx carna test --ci

      - name: Run build
        run: npx carna build --ci
