name: CodeQuality

on: pull_request

jobs:
  qa:
    name: CodeQuality
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
        os: [ubuntu-latest]
        architecture: [x64]
        include:
          # current node LTS on the macOS (intel)
          - node-version: 14.x
            os: macos-latest
            architecture: x64
          # current node LTS on the macOS (arm)
          - node-version: 14.x
            os: macos-latest
            architecture: arm64

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache-node-modules
        with:
          path: node_modules
          key: >-
            npm-install
            -${{ runner.OS }}
            -v${{ matrix.node-version }}
            -${{ matrix.architecture }}
            -${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }} (${{ matrix.architecture }}) on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run carna
        run: npx carna ci
