import { join } from 'path';
import { cfg, cwd, root } from './argv';
import { mockFilePackage } from './packageJson';

const getWorkspaceFiles = (name: string, files: Record<string, boolean> = {}) => ({
  [join(cwd, `packages/${name}/babel.config.js`)]: false,
  [join(cwd, `packages/${name}/babel.config.json`)]: false,
  [join(cwd, `packages/${name}/package.json`)]: true,
  [join(cwd, `packages/${name}/src/index.js`)]: false,
  [join(cwd, `packages/${name}/src/index.ts`)]: true,
  [join(cwd, `packages/${name}/src/lib/app.ts`)]: true,
  [join(cwd, `packages/${name}/tsconfig.json`)]: true,
  ...files,
});

const getAccessFiles = (files: Record<string, boolean> = {}): Record<string, boolean> => ({
  [root]: true,
  [cwd]: true,
  [cfg]: true,
  [mockFilePackage]: true,
  [join(cwd, '.carnarc.json')]: false,
  [join(cwd, '.commitlintrc.js')]: false,
  [join(cwd, '.commitlintrc.json')]: false,
  [join(cwd, '.commitlintrc.yml')]: false,
  [join(cwd, '.eslintrc.cjs')]: false,
  [join(cwd, '.eslintrc.js')]: false,
  [join(cwd, '.eslintrc.json')]: false,
  [join(cwd, '.eslintrc.yaml')]: false,
  [join(cwd, '.eslintrc.yml')]: false,
  [join(cwd, '.eslintrc')]: false,
  [join(cwd, '.git')]: false,
  [join(cwd, '.github')]: false,
  [join(cwd, '.github/ISSUE_TEMPLATE')]: false,
  [join(cwd, '.github/workflows')]: false,
  [join(cwd, '.prettierrc.js')]: false,
  [join(cwd, '.prettierrc.json')]: false,
  [join(cwd, '.prettierrc.toml')]: false,
  [join(cwd, '.prettierrc.yaml')]: false,
  [join(cwd, '.prettierrc.yml')]: false,
  [join(cwd, '.prettierrc')]: false,
  [join(cwd, 'babel.config.js')]: true,
  [join(cwd, 'babel.config.json')]: false,
  [join(cwd, 'commitlint.config.js')]: false,
  [join(cwd, 'coverage', '_e2e', 'coverage-final.json')]: true,
  [join(cwd, 'coverage', '_unit', 'coverage-final.json')]: true,
  [join(cwd, 'jest.config.js')]: true,
  [join(cwd, 'jest.config.ts')]: false,
  [join(cwd, 'node_modules')]: true,
  [join(cwd, 'node_modules/module1/node_modules')]: true,
  [join(cwd, 'node_modules/module1/node_modules/module1-1')]: true,
  [join(cwd, 'node_modules/module1/node_modules/module1-1/node_modules')]: false,
  [join(cwd, 'node_modules/module1/node_modules/module1-1/package.json')]: true,
  [join(cwd, 'node_modules/module1/package.json')]: true,
  [join(cwd, 'node_modules/module2/node_modules')]: false,
  [join(cwd, 'node_modules/module2/package.json')]: true,
  [join(cwd, 'node_modules/module3/node_modules')]: false,
  [join(cwd, 'node_modules/module3/package.json')]: true,
  [join(cwd, 'prettier.config.js')]: false,
  [join(cwd, 'src/index.js')]: false,
  [join(cwd, 'src/index.ts')]: true,
  [join(cwd, 'src/lib/app.ts')]: true,
  [join(cwd, 'tests', 'e2e', 'post.js')]: false,
  [join(cwd, 'tests', 'e2e', 'post.ts')]: false,
  [join(cwd, 'tests', 'e2e', 'pre.js')]: false,
  [join(cwd, 'tests', 'e2e', 'pre.ts')]: false,
  [join(cwd, 'tests', 'unit', 'post.js')]: false,
  [join(cwd, 'tests', 'unit', 'post.ts')]: false,
  [join(cwd, 'tests', 'unit', 'pre.js')]: false,
  [join(cwd, 'tests', 'unit', 'pre.ts')]: false,
  [join(cwd, 'tests')]: true,
  [join(cwd, 'tsconfig.build.json')]: true,
  [join(cwd, 'tsconfig.json')]: true,
  ...getWorkspaceFiles('a'),
  ...getWorkspaceFiles('b'),
  ...getWorkspaceFiles('c'),
  ...files,
});

export { getAccessFiles };
